[versions]
compose-bom = '2022.11.00'
compose-compiler = '1.3.2'
coroutines = '1.6.4'
hilt = '2.44.2'
hsk-ktx = '1.0-beta14'
junit5 = '5.9.1'
lifecycle = '2.5.1'
violet-dreams = '0.1.2'
work = '2.7.1'
kotlin = '1.7.20'
room = '2.4.3'
retrofit = '2.9.0'

[libraries]
android-gradle = 'com.android.tools.build:gradle:7.4.0-rc01'
kotlin-gradle-plugin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
hilt-android-gradle-plugin = { module = 'com.google.dagger:hilt-android-gradle-plugin', version.ref = 'hilt' }

google-services = 'com.google.gms:google-services:4.3.14'
firebase-crashlytics-gradle = 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'

hsk-ktx = { module = 'com.github.mwy3055:hsk-ktx', version.ref = 'hsk-ktx' }
violet-dreams-core = { module = 'com.github.mwy3055.violet-dreams:violet-dreams-core', version.ref = 'violet-dreams' }
violet-dreams-ui = { module = 'com.github.mwy3055.violet-dreams:violet-dreams-ui', version.ref = 'violet-dreams' }

accompanist-drawablepainter = 'com.google.accompanist:accompanist-drawablepainter:0.25.1'
accompanist-pager = 'com.google.accompanist:accompanist-pager:0.23.1'
accompanist-placeholder-material = 'com.google.accompanist:accompanist-placeholder-material:0.23.1'
accompanist-systemuicontroller = 'com.google.accompanist:accompanist-systemuicontroller:0.23.1'

androidx-collection-ktx = 'androidx.collection:collection-ktx:1.2.0'
androidx-core-ktx = 'androidx.core:core-ktx:1.9.0'
androidx-palette-ktx = 'androidx.palette:palette-ktx:1.0.0'

androidx-lifecycle-extensions = 'androidx.lifecycle:lifecycle-extensions:2.2.0'
androidx-lifecycle-reactivestreams-ktx = { module = 'androidx.lifecycle:lifecycle-reactivestreams-ktx', version.ref = 'lifecycle' }
androidx-lifecycle-runtime-ktx = { module = 'androidx.lifecycle:lifecycle-runtime-ktx', version.ref = 'lifecycle' }
androidx-lifecycle-viewmodel-ktx = { module = 'androidx.lifecycle:lifecycle-viewmodel-ktx', version.ref = 'lifecycle' }

androidx-work-runtime-ktx = { module = 'androidx.work:work-runtime-ktx', version.ref = 'work' }
androidx-work-testing = { module = 'androidx.work:work-testing', version.ref = 'work' }

hilt-work = 'androidx.hilt:hilt-work:1.0.0'
hilt-android = { module = 'com.google.dagger:hilt-android', version.ref = 'hilt' }
hilt-compiler = { module = 'com.google.dagger:hilt-compiler', version.ref = 'hilt' }
hilt-compiler-androidx = 'androidx.hilt:hilt-compiler:1.0.0'
hilt-android-testing = { module = 'com.google.dagger:hilt-android-testing', version.ref = 'hilt' }

room-runtime = { module = 'androidx.room:room-runtime', version.ref = 'room' }
room-ktx = { module = 'androidx.room:room-ktx', version.ref = 'room' }
room-compiler = { module = 'androidx.room:room-compiler', version.ref = 'room' }
room-testing = { module = 'androidx.room:room-testing', version.ref = 'room' }

androidx-core-splashscreen = 'androidx.core:core-splashscreen:1.0.0'
androidx-datastore-preferences = 'androidx.datastore:datastore-preferences:1.0.0'
androidx-profileinstaller = 'androidx.profileinstaller:profileinstaller:1.2.0'
androidx-startup-runtime = 'androidx.startup:startup-runtime:1.1.1'

androidx-activity-compose = { module = 'androidx.activity:activity-compose' }
androidx-hilt-navigation-compose = 'androidx.hilt:hilt-navigation-compose:1.0.0'
androidx-lifecycle-viewmodel-compose = 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.0-alpha03'
androidx-paging-compose = 'androidx.paging:paging-compose:1.0.0-alpha17'

androidx-compose-bom = { module = 'androidx.compose:compose-bom', version.ref = 'compose-bom' }
androidx-compose-material = { module = 'androidx.compose.material:material' }
androidx-compose-foundation = { module = 'androidx.compose.foundation:foundation' }
androidx-compose-material-icons-core = { module = 'androidx.compose.material:material-icons-core' }
androidx-compose-material-icons-extended = { module = 'androidx.compose.material:material-icons-extended' }
androidx-compose-material3 = { module = 'androidx.compose.material3:material3' }
androidx-compose-material3-windowsize = { module = 'androidx.compose.material3:material3-window-size-class' }
androidx-compose-ui = { module = 'androidx.compose.ui:ui' }
androidx-compose-ui-test-junit4 = { module = 'androidx.compose.ui:ui-test-junit4' }
androidx-compose-ui-tooling = { module = 'androidx.compose.ui:ui-tooling' }
androidx-compose-ui-tooling-preview = { module = 'androidx.compose.ui:ui-tooling-preview' }

firebase-bom = 'com.google.firebase:firebase-bom:31.1.0'
firebase-crashlytics-ktx = { module = 'com.google.firebase:firebase-crashlytics-ktx' }
firebase-analytics-ktx = { module = 'com.google.firebase:firebase-analytics-ktx' }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

kotlinx-collections-immutable = 'org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5'

kotlinx-coroutines-android = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-android', version.ref = 'coroutines' }
kotlinx-coroutines-core = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core', version.ref = 'coroutines' }
kotlinx-coroutines-test = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-test', version.ref = 'coroutines' }

retrofit = { module = 'com.squareup.retrofit2:retrofit', version.ref = 'retrofit' }
retrofit-converter-gson = { module = 'com.squareup.retrofit2:converter-gson', version.ref = 'retrofit' }
retrofit-coroutines-adapter = 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'

junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter', version.ref = 'junit5' }
junit-vintage-engine = { module = 'org.junit.vintage:junit-vintage-engine', version.ref = 'junit5' }

androidx-test-uiautomaker = 'androidx.test.uiautomator:uiautomator:2.2.0'
androidx-benchmark-macro-junit4 = 'androidx.benchmark:benchmark-macro-junit4:1.1.1'

androidx-test-orchestrator = 'androidx.test:orchestrator:1.4.2'
assertj-core = 'org.assertj:assertj-core:3.23.1'

androidx-junit = 'androidx.test.ext:junit:1.1.4'
androidx-test-espresso-core = 'androidx.test.espresso:espresso-core:3.5.0'

[bundles]
accompanist = ['accompanist-placeholder-material', 'accompanist-systemuicontroller', 'accompanist-drawablepainter', 'accompanist-pager']
compose = [
    'androidx-compose-material',
    'androidx-compose-foundation',
    'androidx-compose-material-icons-core',
    'androidx-compose-material-icons-extended',
    'androidx-compose-material3',
    'androidx-compose-material3-windowsize',
    'androidx-compose-ui',
    'androidx-compose-ui-tooling',
    'androidx-compose-ui-tooling-preview',
    'androidx-activity-compose',
    'androidx-hilt-navigation-compose',
    'androidx-lifecycle-viewmodel-compose',
    'androidx-paging-compose',
]
compose-ui-test = ['androidx-compose-ui-test-junit4']
coroutines = ['kotlinx-coroutines-core', 'kotlinx-coroutines-android']
jetpack = ['androidx-core-splashscreen', 'androidx-datastore-preferences', 'androidx-profileinstaller', 'androidx-startup-runtime']
lifecycle = [
    'androidx-lifecycle-extensions',
    'androidx-lifecycle-reactivestreams-ktx',
    'androidx-lifecycle-runtime-ktx',
    'androidx-lifecycle-viewmodel-ktx',
]
android-test = ['androidx-junit', 'androidx-test-espresso-core']
retrofit = ['retrofit', 'retrofit-converter-gson', 'retrofit-coroutines-adapter']

[plugins]
